  language: python
  python:
    - "3.6"
  script:
    - python main_app.py
  deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_API_KEY
    keep-history: true
    on:
      branch: master
