  language: python
  python:
    - "3.6"
  script:
    - travis_wait 30 python main_app.py
  deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch: master
